# Generated by Django 5.2 on 2025-05-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите фото')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('История', 'История'), ('Ужасы', 'Ужасы')], default='История', max_length=100, verbose_name='Укажите жанр')),
                ('author', models.CharField(default='Иванов Иван', max_length=100)),
                ('description', models.TextField(verbose_name='Укажите описание книги')),
                ('audio_book', models.URLField(verbose_name='Вставьте ссылку аудио книги')),
            ],
        ),
    ]
