# Generated by Django 5.2 on 2025-05-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_size',
            field=models.PositiveIntegerField(default=200, verbose_name='Укажите кол-во страниц'),
        ),
    ]
