# Generated by Django 5.2 on 2025-05-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_page_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page_size',
        ),
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.PositiveIntegerField(default=200, null=True, verbose_name='Укажите кол-во страниц'),
        ),
    ]
