# Generated by Django 5.2.1 on 2025-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
